version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.3.0-fpm
      - image: circleci/mysql:5.7
        command: mysqld --explicit_defaults_for_timestamp=1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    environment:
      - APP_DEBUG: true
      - APP_ENV: testing
      - APP_KEY: base64:y68cnE1NteAxfDSCPDYNShs+VMGuf3tFuEhXKTvvjaw=
      - DB_CONNECTION: circle_test
      - MYSQL_ALLOW_EMPTY_PASSWORD: true

    working_directory: ~/src

    steps:
      - checkout

      # Install PHP Extension
      - run: sudo apt-get update
      - run: sudo apt-get install -y zlib1g-dev libzip-dev mariadb-client libfreetype6-dev libjpeg62-turbo-dev libpng-dev 
      - run: sudo docker-php-ext-install zip pdo_mysql gd

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # run seeding
      - run: php artisan migrate
      

      # run tests!
      - run: php ./vendor/bin/phpunit

      #heroku deploy
      - deploy:
          name: Deploy Master to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
            fi